FROM python:3.10-slim

WORKDIR /app

# Install Python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Copy application code
COPY src/producer /app
COPY config /app/config

# Create data directory
RUN mkdir -p /app/data

CMD ["python", "-u", "event_generator.py"]
